tanslate nuxt-layout.md
translation-gang/nuxt pull request #10
Opened 2024-06-01 12:08 UTC by mnenie

### 📚 Description

Переведена страница /api/components/nuxt-layout

2024-06-01 20:29 UTC, Hekikai requested changes

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +description: "Nuxt предоставляет компонент <NuxtLayout> для отрисовки макетов на страницах и страницах с ошибками."
Nuxt предоставляет компонент <NuxtLayout> для отрисовки лаяута на страницах и страницах с ошибками.  
Предлагаю оставить "лаяут", другие синонимы что-то вообще не в тему (расположение, макет, планировка...)

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +Вы можете использовать компонент `<NuxtLayout />`, чтобы активировать макет `default` в `app.vue` или `error.vue`.
чтобы активировать лаяут `default` в `app.vue` или `error.vue`.

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +- `name`: Укажите имя макета, который будет отрендерен, это может быть строка, реактивная ссылка или вычисляемое свойство. Оно **должно** совпадать с именем соответствующего файла макета в директории
Укажите имя лаяута

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +Пожалуйста, обратите внимание, что имя макета нормализовано с kebab-case, так, если ваш файл макета называется `errorLayout.vue`, он станет `error-layout` при передаче в качестве свойства `name` в `<
что имя лаяута нормализовано с kebab-case; если ваш файл лаяута называется `errorLayout.vue`, он станет `error-layout` при передаче в качестве свойства `name` в `<NuxtLayout />`.

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +Узнать больше о динамических макетах.
Узнать больше о динамических лаяутах.

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +- `fallback`: Если во входной параметр `name` передан недействительный макет, то он не будет отрендерен. Укажите макет `fallback`, который будет отрендерен в таком случае. Он **должен** совпадать с и
передан недействительный лаяут,  
соответствующего файла лаяута в директории

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +`NuxtLayout` также принимает любые дополнительные входные параметры, которые могут потребоваться для передачи в макет. Затем эти пользовательские входные параметры становятся доступными в виде атрибу
передачи в лаяут. Затем эти пользовательские входные параметры доступны в виде атрибутов.

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +## Переходы
https://ru.vuejs.org/guide/built-ins/transition.html  
тут не переводили, так что давай оставим англ версию

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +`<NuxtLayout />` рендерит входящий контент через `<slot />`, который затем оборачивается вокруг компонента Vue `<Transition />`, чтобы активировать переход макета. Чтобы это работало должным образом,
активировать переход лаяута.

2024-06-01 20:29 UTC, Hekikai commented on docs/3.api/1.components/3.nuxt-layout.md
> +Чтобы получить ссылку на компонент макета, используйте `ref.value.layoutRef`.
на компонент лаяута,

2024-06-01 20:35 UTC, mnenie commented on docs/3.api/1.components/3.nuxt-layout.md
> +description: "Nuxt предоставляет компонент <NuxtLayout> для отрисовки макетов на страницах и страницах с ошибками."
сделаю, просто в доке по вью мы писали чет по типу макеты

2024-06-01 20:41 UTC, mnenie commented
@Hekikai исправлено

2024-06-02 05:43 UTC, Ibochkarev approved these changes

2024-06-02 05:43 UTC, merged