feat(docs) Перевод useAsyncData
translation-gang/nuxt pull request #102
Opened 2024-06-07 18:03 UTC by Ibochkarev

### 🔗 Linked issue

resolves #73 

### 📚 Description

feat(docs) Перевод useAsyncData

2024-06-07 19:25 UTC, Hekikai requested changes

2024-06-07 19:25 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +`data`, `pending`, `status` и `error` являются экземплярами Vue refs, и они должны быть получены с помощью `.value` при использовании внутри `<script setup>`, в то время как `refresh`/`execute` являе
```suggestion
`data`, `pending`, `status` и `error` являются `ref``, и они должны быть получены с помощью `.value` при использовании внутри `<script setup>`, в то время как `refresh`/`execute` являются обычными функциями для повторной загрузки данных.
```

2024-06-07 19:25 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +  - `getCachedData`: Предоставьте функцию, которая возвращает кэшированные данные. Возвращаемое значение _null_ или _undefined_ будет вызывать выборку. По умолчанию это: `key => nuxt.isHydrating ? nu
```suggestion
  - `getCachedData`: функция, которая возвращает кэшированные данные. Возвращаемое значение _null_ или _undefined_ будет вызывать выборку данных. По умолчанию это: `key => nuxt.isHydrating ? nuxt.payload.data[key] : nuxt.static.data[key]`, которая кэширует данные, только если включено `payloadExtraction`.
```

2024-06-07 19:25 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +  - `watch`: следить за реактивными источниками, чтобы они автоматически обновлялись
Тут смысл потерялся. Не они обновлялись, а чтобы запрос заново выполнялся наверное, проверь еще раз, пожалуйста

2024-06-07 19:25 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +  - `deep`: возвращать данные в глубокий ref-объект (по умолчанию это `true`). Можно установить значение `false`, чтобы возвращать данные в неглубоком объекте, что может повысить производительность,
```suggestion
  - `deep`: возвращать данные в виде глубокого ref-объекта (по умолчанию это `true`). Можно установить значение `false`, чтобы возвращать данные в виде объекта с неглубокой реактивностью, что может повысить производительность, если ваши данные не нуждаются в этом.
```

2024-06-07 19:25 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +- `pending`: булево значение, указывающее, продолжается ли извлечение данных.
```suggestion
- `pending`: булево значение, указывающее, продолжается ли получение данных.
```

2024-06-07 19:25 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +- `error`: объект ошибки, если выборка данных не удалась.
```suggestion
- `error`: объект ошибки, если получение данных не удалось.
```

2024-06-07 20:18 UTC, Hekikai requested changes

2024-06-07 20:18 UTC, Hekikai commented on docs/3.api/2.composables/use-async-data.md
> +`data`, `pending`, `status` и `error` являются `ref``, и они должны быть получены с помощью `.value` при использовании внутри `<script setup>`, в то время как `refresh`/`execute` являются обычными фу
```suggestion
`data`, `pending`, `status` и `error` являются `ref`, и они должны быть получены с помощью `.value` при использовании внутри `<script setup>`, в то время как `refresh`/`execute` являются обычными функциями для повторной загрузки данных.
```

2024-06-08 04:30 UTC, JonikUl approved these changes

2024-06-08 04:44 UTC, Ibochkarev commented on docs/3.api/2.composables/use-async-data.md
> +  - `watch`: следить за реактивными источниками, чтобы они автоматически обновлялись
```suggestion
  - `watch`: следить за реактивными источниками для автоматического обновления
```

2024-06-08 04:45 UTC, Ibochkarev commented on docs/3.api/2.composables/use-async-data.md
> +  - `watch`: следить за реактивными источниками, чтобы они автоматически обновлялись
@Hekikai Исправил

2024-06-08 05:40 UTC, merged