feat(docs) Перевод композаблов
translation-gang/nuxt pull request #103
Opened 2024-06-07 18:17 UTC by Ibochkarev

### 🔗 Linked issue

resolves #74 

### 📚 Description

feat(docs) Перевод композаблов

2024-06-07 19:28 UTC, Hekikai requested changes

2024-06-07 19:28 UTC, Hekikai commented on docs/3.api/2.composables/use-error.md
> +description: useError композабл возвращает глобальную ошибку Nuxt, которая обрабатывается.
```suggestion
description: useError композабл возвращает глобальную ошибку Nuxt, которая может быть обработана.
```

2024-06-07 19:28 UTC, Hekikai commented on docs/3.api/2.composables/use-error.md
> +Композит возвращает глобальную ошибку Nuxt, которая обрабатывается, и она доступна как для клиента, так и для сервера.
```suggestion
Композабл возвращает глобальную ошибку Nuxt, которая может быть обработана, и она доступна как для клиента, так и для сервера.
```

2024-06-07 19:28 UTC, Hekikai commented on docs/3.api/2.composables/use-error.md
> +`useError` устанавливает ошибку в состояние и создает реактивную, а также SSR-дружественную глобальную ошибку Nuxt для всех компонентов.
```suggestion
`useError` устанавливает состояние ошибке и создает реактивную, SSR-дружественную глобальную ошибку Nuxt для всех компонентов.
```

2024-06-07 19:28 UTC, Hekikai commented on docs/3.api/2.composables/use-hydration.md
> +`useHydration` - это встроенный компонент, который предоставляет возможность задавать данные на стороне сервера при каждом новом HTTP-запросе и получать их на стороне клиента. Таким образом, `useHydr
```suggestion
`useHydration` - это встроенный композабл, который предоставляет возможность задавать данные на стороне сервера при каждом новом HTTP-запросе и получать их на стороне клиента. Таким образом, `useHydration` позволяет вам полностью контролировать цикл гидратации.
```

2024-06-07 20:17 UTC, Hekikai approved these changes

2024-06-08 03:54 UTC, JonikUl approved these changes

2024-06-08 04:26 UTC, merged