feat(docs) Перевод композаблов
translation-gang/nuxt pull request #105
Opened 2024-06-07 18:50 UTC by Ibochkarev

### 🔗 Linked issue

resolves #75 

### 📚 Description

feat(docs) Перевод композаблов

2024-06-07 19:37 UTC, Hekikai requested changes

2024-06-07 19:37 UTC, Hekikai commented on docs/3.api/2.composables/use-lazy-async-data.md
> +По умолчанию, [`useAsyncData`](/docs/api/composables/use-async-data) блокирует навигацию до тех пор, пока его асинхронный обработчик не будет разрешен. `useLazyAsyncData` предоставляет обертку вокруг
```suggestion
По умолчанию, [`useAsyncData`](/docs/api/composables/use-async-data) блокирует навигацию до тех пор, пока его асинхронный обработчик не будет разрешен. `useLazyAsyncData` предоставляет обертку[`useAsyncData`](/docs/api/composables/use-async-data), которая запускает навигацию до разрешения обработчика, установив опцию `lazy` в `true`.
```

2024-06-07 19:37 UTC, Hekikai commented on docs/3.api/2.composables/use-lazy-fetch.md
> +/* Навигация будет происходить до завершения выборки.
```suggestion
/* Навигация будет происходить до завершения получения данных.
```

2024-06-07 19:37 UTC, Hekikai commented on docs/3.api/2.composables/use-request-header.md
> +Вы можете использовать встроенный компонент [`useRequestHeader`](/docs/api/composables/use-request-header) для доступа к любому заголовку входящего запроса на ваших страницах, в компонентах и плагина
```suggestion
Вы можете использовать встроенный композабл [`useRequestHeader`](/docs/api/composables/use-request-header) для доступа к любому заголовку входящего запроса на ваших страницах, в компонентах и плагинах.
```

2024-06-07 19:37 UTC, Hekikai commented on docs/3.api/2.composables/use-request-headers.md
> +Вы можете использовать встроенный компонент [`useRequestHeaders`](/docs/api/composables/use-request-headers) для доступа к заголовкам входящих запросов на ваших страницах, в компонентах и плагинах.
```suggestion
Вы можете использовать встроенный композабл [`useRequestHeaders`](/docs/api/composables/use-request-headers) для доступа к заголовкам входящих запросов на ваших страницах, в компонентах и плагинах.
```

2024-06-07 20:17 UTC, Hekikai approved these changes

2024-06-08 03:47 UTC, JonikUl requested changes

2024-06-08 03:47 UTC, JonikUl commented on docs/3.api/2.composables/use-lazy-fetch.md
> +  // Поскольку posts могут начинаться с null, у вас не будет доступа
Они же не могут начинаться, а могут быть null пока ответ не придет. Выше ты перевел подобную строку вот так:
_"Поскольку count может быть изначально равным null,"_ .

И тут надо наверное примерно так же.

2024-06-08 04:43 UTC, Ibochkarev commented on docs/3.api/2.composables/use-lazy-fetch.md
> +  // Поскольку posts могут начинаться с null, у вас не будет доступа
```suggestion
  // Поскольку posts может быть изначально равным null, у вас не будет доступа
```

2024-06-08 04:43 UTC, Ibochkarev commented on docs/3.api/2.composables/use-lazy-fetch.md
> +  // Поскольку posts могут начинаться с null, у вас не будет доступа
@JonikUl исправил

2024-06-08 05:36 UTC, JonikUl approved these changes

2024-06-08 05:40 UTC, merged