feat(docs) Перевод navigateTo
translation-gang/nuxt pull request #106
Opened 2024-06-07 19:04 UTC by Ibochkarev

### 🔗 Linked issue

resolves #101 

### 📚 Description

feat(docs) Перевод navigateTo

2024-06-07 19:40 UTC, Hekikai requested changes

2024-06-07 19:40 UTC, Hekikai commented on docs/3.api/3.utils/navigate-to.md
> +// произойдет ошибка;
```suggestion
// выкинет ошибку;
```

2024-06-07 19:40 UTC, Hekikai commented on docs/3.api/3.utils/navigate-to.md
> +  По умолчанию `navigateTo` прокладывает заданный маршрут в экземпляр Vue Router на стороне клиента.
```suggestion
  По умолчанию `navigateTo` пробрасывает заданный маршрут в экземпляр Vue Router на стороне клиента.
```

2024-06-07 19:40 UTC, Hekikai commented on docs/3.api/3.utils/navigate-to.md
>      An object accepting the following properties:
Перевести

2024-06-07 20:16 UTC, Hekikai approved these changes

2024-06-08 04:25 UTC, JonikUl requested changes

2024-06-08 04:25 UTC, JonikUl commented on docs/3.api/3.utils/navigate-to.md
> +Функция `navigateTo` доступна как на сервере, так и на клиенте. Его можно использовать внутри [Nuxt-контекста](/docs/guide/going-further/nuxt-app#the-nuxt-context) или напрямую для осуществления пост
Ее можно использовать...

Это же функция)

2024-06-08 04:41 UTC, Ibochkarev commented on docs/3.api/3.utils/navigate-to.md
> +Функция `navigateTo` доступна как на сервере, так и на клиенте. Его можно использовать внутри [Nuxt-контекста](/docs/guide/going-further/nuxt-app#the-nuxt-context) или напрямую для осуществления пост
```suggestion
Функция `navigateTo` доступна как на сервере, так и на клиенте. Ее можно использовать внутри [Nuxt-контекста](/docs/guide/going-further/nuxt-app#the-nuxt-context) или напрямую для осуществления постраничной навигации.
```

2024-06-08 04:41 UTC, merged