feat(docs) Перевод definePageMeta
translation-gang/nuxt pull request #108
Opened 2024-06-07 19:22 UTC by Ibochkarev

### 🔗 Linked issue

resolves #100 

### 📚 Description

feat(docs) Перевод definePageMeta

2024-06-07 19:46 UTC, Hekikai requested changes

2024-06-07 19:46 UTC, Hekikai commented on docs/3.api/3.utils/define-page-meta.md
> +`definePageMeta` - это макрос компилятора, который вы можете использовать для установки метаданных для ваших компонентов **page**, расположенных в директории [`pages/`](/docs/guide/directory-structur
```suggestion
`definePageMeta` - это макрос компилятора, который вы можете использовать для установки метаданных для ваших компонентов **page**, расположенных в директории [`pages/`](/docs/guide/directory-structure/pages) (если [не указано иное](/docs/api/nuxt-config#page)). Таким образом, вы можете настроить пользовательские метаданные для каждого статического или динамического маршрута вашего следующего приложения.
```

2024-06-07 19:46 UTC, Hekikai commented on docs/3.api/3.utils/define-page-meta.md
> +    Вы можете определить [пользовательское регулярное выражение](#using-a-custom-regular-expression), если у вас более сложный шаблон, чем может быть выражен с помощью имени файла.
```suggestion
    Вы можете определить [пользовательское регулярное выражение](#using-a-custom-regular-expression), если у вас более сложный шаблон, чем имя файла.
```

2024-06-07 19:46 UTC, Hekikai commented on docs/3.api/3.utils/define-page-meta.md
> +    DОпределение анонимного или именованного middleware непосредственно в definePageMeta. Узнайте больше о [middleware маршрутизации](/docs/guide/directory-structure/middleware).
```suggestion
    Определение анонимного или именованного middleware непосредственно в definePageMeta. Узнайте больше о [middleware маршрутизации](/docs/guide/directory-structure/middleware).
```

2024-06-07 19:46 UTC, Hekikai commented on docs/3.api/3.utils/define-page-meta.md
> +  // ... или строка
```suggestion
  // ... или в виде строки
```

2024-06-07 19:46 UTC, Hekikai commented on docs/3.api/3.utils/define-page-meta.md
> +  // ... или несколько строк
```suggestion
  // ... или в виде нескольких строк
```

2024-06-07 19:46 UTC, Hekikai commented on docs/3.api/3.utils/define-page-meta.md
> +Вы можете определить макет, который соответствует имени файла макета, расположенного (по умолчанию) в [директории `layouts/`](/docs/guide/directory-structure/layouts). Вы также можете отключить лейау
```suggestion
Вы можете определить лэйаут, который соответствует имени файла макета, расположенного (по умолчанию) в [директории `layouts/`](/docs/guide/directory-structure/layouts). Вы также можете отключить лейаут, установив для layout значение `false`:
```

2024-06-07 20:16 UTC, Hekikai approved these changes

2024-06-08 03:37 UTC, JonikUl approved these changes

2024-06-08 04:26 UTC, merged