translate: nuxt-loading-indicator
translation-gang/nuxt pull request #109
Opened 2024-06-07 20:19 UTC by mnenie

### 🔗 Linked issue

issue #50

### 📚 Description

Переведена страница /api/components/nuxt-loading-indicator

2024-06-07 20:36 UTC, Hekikai requested changes

2024-06-07 20:36 UTC, Hekikai commented on docs/3.api/1.components/5.nuxt-loading-indicator.md
> +Вы можете подключиться к основному инстансу индикатора instance, используя [`useLoadingIndicator` композабл](/docs/api/composables/use-loading-indicator), который позволит вам самостоятельно запускат
```suggestion
Вы можете подключиться к основному инстансу индикатора instance, используя композабл [`useLoadingIndicator`](/docs/api/composables/use-loading-indicator), который позволит вам самостоятельно запускать события запуска/завершения.
```

2024-06-07 20:41 UTC, Ibochkarev commented on docs/3.api/1.components/5.nuxt-loading-indicator.md
> +Вы можете подключиться к основному инстансу индикатора instance, используя композабл [`useLoadingIndicator`](/docs/api/composables/use-loading-indicator), который позволит вам самостоятельно запускат
Instance остался

2024-06-07 20:42 UTC, mnenie commented on docs/3.api/1.components/5.nuxt-loading-indicator.md
> +Вы можете подключиться к основному инстансу индикатора instance, используя композабл [`useLoadingIndicator`](/docs/api/composables/use-loading-indicator), который позволит вам самостоятельно запускат
увидел, сейчас исправлю

2024-06-07 21:05 UTC, Ibochkarev approved these changes

2024-06-08 05:33 UTC, JonikUl approved these changes

2024-06-08 05:40 UTC, merged