feat(docs) Перевод композаблов
translation-gang/nuxt pull request #129
Opened 2024-06-08 08:13 UTC by Ibochkarev

### 🔗 Linked issue

resolves #76

### 📚 Description

feat(docs) Перевод композаблов

2024-06-08 08:19 UTC, Hekikai requested changes

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-request-url.md
> +При использовании [Hybrid Rendering](/docs/guide/concepts/rendering#hybrid-rendering) со стратегиями кэширования, все заголовки входящих запросов отбрасываются при обработке кэшированных ответов чере
```suggestion
При использовании [гибридного рендеринга](/docs/guide/concepts/rendering#hybrid-rendering) со стратегиями кэширования, все заголовки входящих запросов отбрасываются при обработке кэшированных ответов через [слой кэширования Nitro](https://nitro.unjs.io/guide/cache) (то есть `useRequestURL` будет возвращать `localhost` для `host`).
```

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-route.md
> +Помимо динамических параметров и параметров запроса, `useRoute()` также предоставляет следующие вычисляемые ссылки, связанные с текущим маршрутом:
```suggestion
Помимо динамических параметров и query-параметров, `useRoute()` также предоставляет следующие вычисляемые ссылки, связанные с текущим маршрутом:
```

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-route.md
> +::примечание
```suggestion
::note
```

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-seo-meta.md
> +Это помогает вам избежать распространенных ошибок, таких как использование `name` вместо `property`, а также опечаток - с более чем 100+ мета-тегами, полностью прописанными.
```suggestion
Это помогает вам избежать распространенных ошибок, таких как использование `name` вместо `property`, а также опечаток - с более чем полностью прописанными 100+ мета-тегами.
```

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-seo-meta.md
> +При вставке реактивных тегов вы должны использовать вычисляемый синтаксис геттера (`() => value`):
```suggestion
При вставке реактивных тегов вы должны использовать синтаксик вычисляемого геттера (`() => value`):
```

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-state.md
> +Поскольку данные внутри `useState` будут сериализованы в JSON, важно, чтобы они не содержали ничего, что нельзя сериализовать, например, классы, функции или символы.
```suggestion
Поскольку данные внутри `useState` будут сериализованы в JSON, важно, чтобы они не содержали ничего, что нельзя сериализовать, например, классы, функции или symbol.
```

2024-06-08 08:19 UTC, Hekikai commented on docs/3.api/2.composables/use-state.md
> +- `key`: Уникальный ключ, который гарантирует, что выборка данных правильно дедублируется по запросам. Если вы не предоставите ключ, то будет сгенерирован ключ, уникальный для файла и номера строки э
```suggestion
- `key`: Уникальный ключ, который гарантирует, что получение данных правильно дедублируется по запросам. Если вы не предоставите ключ, то будет сгенерирован ключ, уникальный для файла и номера строки экземпляра [`useState`](/docs/api/composables/use-state).
```

2024-06-08 08:27 UTC, Ibochkarev commented on docs/3.api/2.composables/use-route.md
> +::примечание
Это не переводится

2024-06-08 14:30 UTC, Hekikai approved these changes

2024-06-09 06:46 UTC, JonikUl approved these changes

2024-06-09 06:46 UTC, merged