feat(docs): Перевод nuxt-link
translation-gang/nuxt pull request #130
Opened 2024-06-08 19:37 UTC by mnenie

### 🔗 Linked issue

resolves https://github.com/translation-gang/nuxt/issues/49

### 📚 Description

Переведена страница /api/components/nuxt-link

2024-06-08 19:40 UTC, mnenie commented
вопрос
Есть предложение - ... когда включено, будет выполняться предварительная загрузка middleware, layouts и payloads
layout у нас переведено как лэйаут, но про middleware условно он остался как middleware 
как тут быть? тут либо оставлять одинаково, либо переводить middleware

2024-06-09 06:51 UTC, JonikUl approved these changes

2024-06-09 10:00 UTC, Hekikai requested changes

2024-06-09 10:43 UTC, Hekikai approved these changes

2024-06-09 10:45 UTC, merged