feat(docs): перевод nuxt-island
translation-gang/nuxt pull request #160
Opened 2024-06-10 20:17 UTC by mnenie

### 🔗 Linked issue

resolves https://github.com/translation-gang/nuxt/issues/53

### 📚 Description

Переведена страница /api/components/nuxt-island

2024-06-10 20:26 UTC, Ibochkarev commented on docs/3.api/1.components/8.nuxt-island.md
> +Удаленным островам необходимо, чтобы `experimental.componentIslands` были  `'local+remote'` в вашем `nuxt.config`.
```suggestion
Удаленным островам необходимо, чтобы `experimental.componentIslands` были `'local+remote'` в вашем `nuxt.config`.
```

2024-06-11 02:54 UTC, JonikUl approved these changes

2024-06-11 07:22 UTC, Hekikai requested changes

2024-06-11 07:22 UTC, Hekikai commented on docs/3.api/1.components/8.nuxt-island.md
> +  - **описание**: принудительная повторная загрузка серверного компонента путем его повторной загрузки.
```suggestion
  - **описание**: принудительная повторная загрузка серверного компонента.
```

2024-06-11 07:35 UTC, Ibochkarev approved these changes

2024-06-11 07:35 UTC, merged