feat(docs): Перевод nuxt-router-announcer
translation-gang/nuxt pull request #169
Opened 2024-06-12 17:37 UTC by mnenie

### 🔗 Linked issue

resolves https://github.com/translation-gang/nuxt/issues/57

### 📚 Description

Переведена страница /api/components/nuxt-router-announcer

2024-06-12 19:30 UTC, Hekikai requested changes

2024-06-12 19:30 UTC, Hekikai commented on docs/3.api/1.components/12.nuxt-route-announcer.md
> +- `atomic`: Определяет, будут ли программы чтения с экрана сообщать только об изменениях или обо всем содержимом. Установите значение true для полного содержимого, считываемого при обновлениях, и зна
```suggestion
- `atomic`: Определяет, будут ли программы чтения с экрана сообщать только об изменениях или обо всем содержимом. Установите значение `true` для полного содержимого, считываемого при обновлениях, и значение `false` только для считываний изменений. (по умолчанию `false`)
```

2024-06-12 20:20 UTC, Hekikai approved these changes

2024-06-13 02:04 UTC, Ibochkarev approved these changes

2024-06-13 02:04 UTC, merged