feat(docs) Перевод Meta Tags
translation-gang/nuxt pull request #175
Opened 2024-06-13 16:52 UTC by Ibochkarev

### 🔗 Linked issue

resolves #151 

### 📚 Description

feat(docs) Перевод Meta Tags

2024-06-13 17:45 UTC, mnenie commented on docs/7.migration/4.meta.md
> +В настоящее время Nuxt использует [`vueuse/head`](https://github.com/vueuse/head) для управления метатегами, но детали реализации могут измениться.
тут метатегами написано слитно, везде мета-теги(-тегами)

2024-06-13 17:47 UTC, mnenie commented on docs/7.migration/4.meta.md
> +// если используется метод head Options API, необходимо использовать `defineNuxtComponent`
head -> `head`

2024-06-13 17:53 UTC, mnenie commented on docs/7.migration/4.meta.md
> +2. С помощью [`useHead`](/docs/api/composables/use-head) [composable](/docs/getting-started/seo-meta)
composable не переведен -> С помощью композабла `useHead`

2024-06-13 20:41 UTC, Hekikai requested changes

2024-06-13 20:41 UTC, Hekikai commented on docs/7.migration/4.meta.md
> +2. С помощью [`useHead`](/docs/api/composables/use-head) [composable](/docs/getting-started/seo-meta)
```suggestion
2. С помощью композабла [`useHead`](/docs/api/composables/use-head)
```

2024-06-13 20:41 UTC, Hekikai commented on docs/7.migration/4.meta.md
> +// если используется метод head Options API, необходимо использовать `defineNuxtComponent`
```suggestion
// если используется метод `head` Options API, необходимо использовать `defineNuxtComponent`
```

2024-06-14 03:28 UTC, Ibochkarev commented on docs/7.migration/4.meta.md
> +В настоящее время Nuxt использует [`vueuse/head`](https://github.com/vueuse/head) для управления метатегами, но детали реализации могут измениться.
```suggestion
В настоящее время Nuxt использует [`vueuse/head`](https://github.com/vueuse/head) для управления мета-тегами, но детали реализации могут измениться.
```

2024-06-14 03:50 UTC, alexeyvokin commented on docs/7.migration/4.meta.md
> +Nuxt 3 также предоставляет мета-компоненты, которые вы можете использовать для выполнения того же задания. Хотя эти компоненты похожи на теги HTML, они предоставляются Nuxt и имеют схожую функциональ
```suggestion
Nuxt 3 также предоставляет мета-компоненты, которые вы можете использовать для выполнения той же задачи. Хотя эти компоненты похожи на теги HTML, они предоставляются Nuxt и имеют схожую функциональность.
```

`задание` как-то больше к учебному процессу как-будто бы относится, или при делегировании работы кому-то

2024-06-14 04:52 UTC, alexeyvokin approved these changes

2024-06-14 04:52 UTC, mnenie approved these changes

2024-06-14 04:56 UTC, merged