feat(docs) Перевод Pages and Layouts
translation-gang/nuxt pull request #176
Opened 2024-06-13 17:27 UTC by Ibochkarev

### 🔗 Linked issue

resolves #152 

### 📚 Description

feat(docs) Перевод Pages and Layouts

2024-06-13 20:50 UTC, Hekikai requested changes

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +Этот файл является отличным местом для размещения любого пользовательского кода, который необходимо выполнить один раз при запуске приложения, а также любых компонентов, присутствующих на всех страни
```suggestion
Этот файл является отличным местом для размещения любого пользовательского кода, который необходимо выполнить один раз при запуске приложения, а также любых компонентов, присутствующих на всех страницах вашего приложения. Например, если у вас есть только один лейаут, вы можете переместить его в `app.vue`.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +В Nuxt 2 для отображения текущей страницы в слое используется компонент `<Nuxt>`. В Nuxt 3 слои используют слоты, поэтому вам придется заменить этот компонент на `<slot />`. Это также позволяет испол
```suggestion
В Nuxt 2 для отображения текущей страницы в лейауте используется компонент `<Nuxt>`. В Nuxt 3 лейауты используют слоты, поэтому вам придется заменить этот компонент на `<slot />`. Это также позволяет использовать продвинутые случаи использования с именованными и локальными слотами. [Подробнее о слоях](/docs/guide/directory-structure/layouts).
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +title: Страницы и Слои
```suggestion
title: Страницы и Лейауты
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +description: Узнайте, как мигрировать со страниц и слоев Nuxt 2 на Nuxt 3.
```suggestion
description: Узнайте, как мигрировать со страниц и лейаутов Nuxt 2 на Nuxt 3.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +## Слои
```suggestion
## Лейаут
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +Если вы используете слои в своем приложении для нескольких страниц, требуется внести незначительные изменения.
```suggestion
Если вы используете лейауты в своем приложении для нескольких страниц, требуется внести незначительные изменения.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +Вам также потребуется изменить способ определения слоя, используемого страницей, с помощью макроса компилятора `definePageMeta`. Слои будут записаны в kebab-case. Таким образом, `layouts/customLayout
```suggestion
Вам также потребуется изменить способ определения лейаута, используемого страницей, с помощью макроса компилятора `definePageMeta`. Лейауты будут записаны в kebab-case. Таким образом, `layouts/customLayout.vue` становится `custom-layout` при ссылке на вашу страницу.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +2. Используйте [`definePageMeta`](/docs/api/utils/define-page-meta) чтобы выбрать слой, используемый вашей страницей.
```suggestion
2. Используйте [`definePageMeta`](/docs/api/utils/define-page-meta), чтобы выбрать лейаут, используемый вашей страницей.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +3. Переместите `~/layouts/_error.vue` в `~/error.vue`. См. [документацию по обработке ошибок](/docs/getting-started/error-handling). Если вы хотите обеспечить использование этой страницы слоем, вы мо
```suggestion
3. Переместите `~/layouts/_error.vue` в `~/error.vue`. См. [документацию по обработке ошибок](/docs/getting-started/error-handling). Если вы хотите обеспечить использование этого лейаута страницей, вы можете использовать  [`<NuxtLayout>`](/docs/guide/directory-structure/layouts) непосредственно в `error.vue`:
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +### Transitions страницы и слоев
```suggestion
### Transitions страницы и лейаутов
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +Если вы определяли транзиции для вашей страницы или слоя непосредственно в опциях компонента, теперь вам потребуется использовать definePageMeta, чтобы установить транзицию. С Vue 3 [классы -enter и
```suggestion
Если вы определяли transitions для вашей страницы или лейаута непосредственно в опциях компонента, теперь вам потребуется использовать definePageMeta, чтобы установить transition. С Vue 3 [классы -enter и -leave CSS classes были переименованы](https://v3-migration.vuejs.org/breaking-changes/transition.html). Свойство `style` из `<Nuxt>` больше не применяется к transition при использовании на `<slot>`, поэтому переместите стили в ваш класс `-active`.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +  // вы также можете передать строку или computed свойство
```suggestion
  // вы также можете передать строку или computed-свойство
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +При миграции с Nuxt 2 на Nuxt 3 вам придется обновить способ программной навигации пользователей. В Nuxt 2 у вас был доступ к базовому Vue Router с помощью `this.$router`. В Nuxt 3 вы можете использо
```suggestion
При миграции с Nuxt 2 на Nuxt 3 вам придется обновить способ программной навигации пользователей. В Nuxt 2 у вас был доступ к базовому Vue Router с помощью `this.$router`. В Nuxt 3 вы можете использовать утилиту `navigateTo()`, которая позволяет передать маршрут и параметры во Vue Router.
```

2024-06-13 20:50 UTC, Hekikai commented on docs/7.migration/6.pages-and-layouts.md
> +Убедитесь, что всегда ожидайте [`navigateTo`](/docs/api/utils/navigate-to) или цепочку его результата, возвращая из функций.
```suggestion
Убедитесь, что всегда используете `await` перед [`navigateTo`](/docs/api/utils/navigate-to) или chain его результата, возвращая из функций.
```

2024-06-13 20:50 UTC, Hekikai commented
@Ibochkarev внимательно просмотри еще все раз - Layout !== слой!! Слой у нас используется в Layer, будет мешанина, если не исправим)))

2024-06-14 04:29 UTC, alexeyvokin requested changes

2024-06-14 04:29 UTC, alexeyvokin commented on docs/7.migration/6.pages-and-layouts.md
> +Вам также потребуется изменить способ определения лейаута, используемого страницей, с помощью макроса компилятора `definePageMeta`. Лейауты будут записаны в kebab-case. Таким образом, `layouts/custom
```suggestion
Вам также потребуется изменить способ определения лейаута, используемого страницей, с помощью макроса компилятора `definePageMeta`. Лейауты будут записаны в kebab-case. Таким образом, `layouts/customLayout.vue` становится `custom-layout` при использовании на вашей странице.
```

2024-06-14 04:29 UTC, alexeyvokin commented on docs/7.migration/6.pages-and-layouts.md
> +3. Переместите `~/layouts/_error.vue` в `~/error.vue`. См. [документацию по обработке ошибок](/docs/getting-started/error-handling). Если вы хотите обеспечить использование этого лейаута страницей, в
```suggestion
3. Переместите `~/layouts/_error.vue` в `~/error.vue`. См. [документацию по обработке ошибок](/docs/getting-started/error-handling). Если вы хотите гарантировать, что на этой странице используется лейаут, вы можете использовать  [`<NuxtLayout>`](/docs/guide/directory-structure/layouts) непосредственно в `error.vue`:
```

2024-06-14 04:29 UTC, alexeyvokin commented on docs/7.migration/6.pages-and-layouts.md
> +3. Если вы используете Composition API, вы также можете мигрировать `this.$route` и `this.$router` для использования [`useRoute`](/docs/api/composables/use-route) и [`useRouter`](/docs/api/composable
```suggestion
3. Если вы используете Composition API, вы также можете заменить `this.$route` и `this.$router` на композаблы [`useRoute`](/docs/api/composables/use-route) и [`useRouter`](/docs/api/composables/use-router).
```

2024-06-14 04:29 UTC, alexeyvokin commented on docs/7.migration/6.pages-and-layouts.md
> +Большая часть синтаксиса и функциональности остается прежней для глобального компонента [NuxtLink](/docs/api/components/nuxt-link). Если вы использовали сокращенный формат <NLink>, вам следует обнови
```suggestion
Большая часть синтаксиса и функциональности остается прежней для глобального компонента [NuxtLink](/docs/api/components/nuxt-link). Если вы использовали сокращенный формат `<NLink>`, вам следует заменить его на `<NuxtLink>`.
```

2024-06-14 04:29 UTC, alexeyvokin commented on docs/7.migration/6.pages-and-layouts.md
> +При миграции с Nuxt 2 на Nuxt 3 вам придется обновить способ программной навигации пользователей. В Nuxt 2 у вас был доступ к базовому Vue Router с помощью `this.$router`. В Nuxt 3 вы можете использо
мне кажется, что `базовому` можно опустить, т.к. какой-то лишний контекст вносит, и так понятно, что это пакет Vue Router

либо лучше перевести как `лежащему в основе`

2024-06-14 04:39 UTC, Ibochkarev commented on docs/7.migration/6.pages-and-layouts.md
> +При миграции с Nuxt 2 на Nuxt 3 вам придется обновить способ программной навигации пользователей. В Nuxt 2 у вас был доступ к базовому Vue Router с помощью `this.$router`. В Nuxt 3 вы можете использо
```suggestion
При миграции с Nuxt 2 на Nuxt 3 вам придется обновить способ программной навигации пользователей. В Nuxt 2 у вас был доступ к Vue Router с помощью `this.$router`. В Nuxt 3 вы можете использовать утилиту `navigateTo()`, которая позволяет передать маршрут и параметры во Vue Router.
```

2024-06-14 06:44 UTC, alexeyvokin commented on docs/7.migration/6.pages-and-layouts.md
> +Если вы определяли transitions для вашей страницы или лейаута непосредственно в опциях компонента, теперь вам потребуется использовать definePageMeta, чтобы установить transition. С Vue 3 [классы -en
```suggestion
Если вы определяли transitions для вашей страницы или лейаута непосредственно в опциях компонента, теперь вам потребуется использовать `definePageMeta`, чтобы установить transition. С Vue 3 [CSS-классы -enter и -leave были переименованы](https://v3-migration.vuejs.org/breaking-changes/transition.html). Свойство `style` из `<Nuxt>` больше не применяется к transition при использовании на `<slot>`, поэтому переместите стили в ваш класс `-active`.
```

2024-06-14 07:07 UTC, Hekikai approved these changes

2024-06-14 07:19 UTC, merged