feat(docs): Локализация docs/getting-started/error-handling.md (#21)
translation-gang/nuxt pull request #182
Opened 2024-06-14 21:56 UTC by romanxlee

🔗 Linked issue
resolves https://github.com/translation-gang/nuxt/issues/21

📚 Description
Локализация docs/getting-started/error-handling.md

2024-06-15 10:06 UTC, mnenie commented on docs/1.getting-started/8.error-handling.md
> +Настройте страницу ошибки по умолчанию добавив `~/error.vue` в исходной папке вашего приложения, рядом с `app.vue`.
тут не совсем корректно написано (добавив "что-то" в исходной папке...)

можно написать так: Настройте страницу ошибки по умолчанию, добавив `~/error.vue` в исходную директорию вашего приложения рядом с `app.vue`.

2024-06-16 06:23 UTC, JonikUl requested changes

2024-06-16 06:23 UTC, JonikUl commented on docs/1.getting-started/8.error-handling.md
> +Обязательно проверяйте перед использованием чего-либо, зависящего от Nuxt плагинов, напрмер `$route` или `useRouter`, так как если плагин кинет ошибку, он не перезапуститься, пока вы не очистите ошиб
```suggestion
Обязательно проверяйте перед использованием чего-либо, зависящего от Nuxt плагинов, напрмер `$route` или `useRouter`, так как если плагин кинет ошибку, он не перезапустится, пока вы не очистите ошибку.
```

2024-06-16 09:30 UTC, JonikUl approved these changes

2024-06-16 09:32 UTC, mnenie approved these changes

2024-06-16 09:48 UTC, merged