feat(docs) Перевод документации Overview
translation-gang/nuxt pull request #197
Opened 2024-06-19 04:00 UTC by Ibochkarev

### 🔗 Linked issue

resolves #141 

### 📚 Description

feat(docs) Перевод документации Overview

2024-06-19 06:29 UTC, mnenie requested changes

2024-06-19 06:29 UTC, mnenie commented on docs/6.bridge/1.overview.md
> +Bridge - это слой обратной совместимости, который позволяет вам использовать многие новые функции Nuxt 3 просто установив и включив модуль Nuxt.
```suggestion
Bridge - это слой обратной совместимости, который позволяет вам использовать многие новые функции Nuxt 3, просто установив и включив модуль Nuxt.
```

2024-06-19 06:29 UTC, mnenie commented on docs/6.bridge/1.overview.md
> +После завершения установки убедитесь, что как сборка для разработки, так и для продакшена работают как ожидалось, прежде чем продолжать.
```suggestion
После завершения установки убедитесь, что сборка как для разработки, так и для продакшена работают как ожидалось, прежде чем продолжать.
```

2024-06-19 06:29 UTC, mnenie commented on docs/6.bridge/1.overview.md
> +Убедитесь избегать любого синтаксиса CommonJS, такого как `module.exports`, `require` или `require.resolve` в файле конфигурации. Это скоро будет устаревшим и не будет поддерживаться.
```suggestion
Пожалуйста, старайтесь избегать любого синтаксиса CommonJS, такого как `module.exports`, `require` или `require.resolve` в файле конфигурации. Это скоро будет устаревшим и не будет поддерживаться.
```

2024-06-19 06:29 UTC, mnenie commented on docs/6.bridge/1.overview.md
> +Убедитесь, что ваш сервер разработки (`nuxt dev`) не работает, удалите любые файлы блокировки пакетов (`package-lock.json` и `yarn.lock`), и установите последнюю версию Nuxt 2:
```suggestion
Убедитесь, что ваш сервер разработки (`nuxt dev`) не работает, удалите любые файлы блокировки пакетов (`package-lock.json` и `yarn.lock`) и установите последнюю версию Nuxt 2:
```

2024-06-19 07:01 UTC, mnenie approved these changes

2024-06-20 02:31 UTC, JonikUl approved these changes

2024-06-20 02:31 UTC, JonikUl commented on docs/6.bridge/1.overview.md
> +Пожалуйста, старайтесь избегать любого синтаксиса CommonJS, такого как `module.exports`, `require` или `require.resolve` в файле конфигурации. Это скоро будет устаревшим и не будет поддерживаться.
```suggestion
Пожалуйста, старайтесь избегать любого синтаксиса CommonJS, такого как `module.exports`, `require` или `require.resolve` в файле конфигурации. Это скоро будет объявлено устаревшим и не будет поддерживаться.
```

2024-06-20 02:31 UTC, JonikUl commented on docs/6.bridge/1.overview.md
> +Используя Nuxt Bridge, вы можете убедиться, что ваш проект (почти) готов к Nuxt 3, и вы можете постепенно переходить на Nuxt 3.
```suggestion
Используя Nuxt Bridge, вы можете убедиться, что ваш проект (почти) готов к Nuxt 3, и вы можете постепенно переходить на него.
```

2024-06-20 03:14 UTC, merged