feat(docs): Локализация docs/guide/concepts/rendering.md (#31)
translation-gang/nuxt pull request #204
Opened 2024-06-21 12:39 UTC by romanxlee

🔗 Linked issue
resolves https://github.com/translation-gang/nuxt/issues/31

📚 Description
Локализация docs/guide/concepts/rendering.md

2024-06-22 03:42 UTC, JonikUl requested changes

2024-06-22 03:42 UTC, JonikUl commented on docs/2.guide/1.concepts/3.rendering.md
> +По умолчанию Nuxt использует **универсальный рендеринг**, чтобы обеспечить лучший пользовательский опыт, производительность и оптимизировать индексацию поисковыми системами, но вы можете переключать
```suggestion
По умолчанию Nuxt использует **универсальный рендеринг**, чтобы обеспечить лучший пользовательский опыт, производительность и оптимизировать индексацию поисковыми системами, но вы можете переключать режимы рендеринга в [одной строке конфигурации](/docs/api/nuxt-config#ssr).
```

2024-06-22 03:42 UTC, JonikUl commented on docs/2.guide/1.concepts/3.rendering.md
> +- **Стоимость:** Должен быть запущен сервер, чтобы отображать страницы «на лету». Это добавляет ежемесячные расходы, как и любой традиционный сервер. Однако количество вызовов сервера значительно сок
```suggestion
- **Стоимость:** Чтобы отображать страницы «на лету», должен быть запущен сервер. Это добавляет ежемесячные расходы, как и у любого традиционного сервера. Однако количество вызовов сервера значительно сокращается благодаря универсальному рендерингу, когда браузер берет на себя навигацию на стороне клиента. Снижение затрат возможно за счет использования [пограничного рендеринга](#edge-side-rendering).
```

2024-06-22 03:42 UTC, JonikUl commented on docs/2.guide/1.concepts/3.rendering.md
> +- **Производительность**: Пользователю приходится ждать, пока браузер загрузит, проанализирует и запустит файлы JavaScript. Это может занять некоторое время и повлиять на работу пользователя, в завис
```suggestion
- **Производительность**: Пользователю приходится ждать, пока браузер загрузит, проанализирует и запустит файлы JavaScript. Это может занять некоторое время и повлиять на пользовательский опыт, в зависимости от сети для загрузки и устройства пользователя для парсинга и выполнения.
```

2024-06-22 03:42 UTC, JonikUl commented on docs/2.guide/1.concepts/3.rendering.md
> +Если вы успользуете `ssr: false`, вы должны расположить HTML-файл в `~/app/spa-loading-template.html` с некоторым HTML-кодом, который вы хотите использовать для рендеринга экрана загрузки, который бу
```suggestion
Если вы успользуете `ssr: false`, вы должны расположить в `~/app/spa-loading-template.html` HTML-файл с некоторым HTML-кодом, который вы хотите использовать для рендеринга экрана загрузки, который будет отображаться до тех пор, пока ваше приложение не будет гидрировано.
```

2024-06-22 03:42 UTC, JonikUl commented on docs/2.guide/1.concepts/3.rendering.md
> +- `appMiddleware: string | string[] | Record<string, boolean>`{lang=ts} - Позволяет вам middleware, которое должно или не должно работать для путей к страницам в части приложения Vue вашего приложени
```suggestion
- `appMiddleware: string | string[] | Record<string, boolean>`{lang=ts} - Позволяет вам определить middleware, которое должно или не должно запускаться для путей к страницам в части Vue вашего приложения (то есть не для ваших маршрутов Nitro).
```

2024-06-22 18:24 UTC, Hekikai requested changes

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Nuxt поддерживает разные режимы рендеринга: [универсальный рендеринг](#universal-rendering), [рендеринг на стороне клиента](#client-side-rendering), а также предоставляет [гибридный рендеринг](#hybri
```suggestion
Nuxt поддерживает разные режимы рендеринга: [универсальный рендеринг](#universal-rendering), [рендеринг на стороне клиента](#client-side-rendering), а также предоставляет [гибридный рендеринг](#hybrid-rendering) и возможность рендерить ваше приложение на [пограничных CDN-серверах](#edge-side-rendering).
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Когда браузер запрашивает URL-адрес с включенным универсальным (серверным + клиентским) рендерингом, сервер возвращает браузеру полностью отрисованную HTML-страницу. Независимо от того, была ли стран
```suggestion
Когда браузер запрашивает URL-адрес с включенным универсальным (серверным + клиентским) рендерингом, сервер возвращает браузеру полностью отрисованную HTML-страницу. Независимо от того, была ли страница сгенерирована заранее и кэширована или отрисовывается налету, в какой-то момент Nuxt запустил код JavaScript (Vue.js) в среде сервера, создав HTML-документ. Пользователи сразу получают контент нашего приложения, в отличие от рендеринга на стороне клиента. Этот шаг аналогичен традиционному **рендерингу на стороне сервера**, выполняемому приложениями PHP или Ruby.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Чтобы не потерять преимущества метода рендеринга на стороне клиента, такие как динамические интерфейсы и переходы страниц, Клиент (браузер) загружает код JavaScript, который запускается на Сервере в
```suggestion
Чтобы не потерять преимущества метода рендеринга на стороне клиента, такие как динамические интерфейсы и переходы страниц, клиент (браузер) загружает код JavaScript, который запускается на сервере в фоновом режиме после загрузки HTML-документа. Браузер интерпретирует его снова (отсюда и **универсальный рендеринг**), а Vue.js берет на себя управление документом и обеспечивает интерактивность.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Универсальный рендеринг позволяет Nuxt приложению обеспечить быструю загрузку страницы, сохраняя при этом преимущества рендеринга на стороне клиента. Более того, поскольку контент уже присутствует в
```suggestion
Универсальный рендеринг позволяет Nuxt-приложению обеспечить быструю загрузку страницы, сохраняя при этом преимущества рендеринга на стороне клиента. Более того, поскольку контент уже присутствует в HTML-документе, поисковые роботы могут индексировать его без дополнительных затрат.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +- **Стоимость:** Чтобы отображать страницы «на лету», должен быть запущен сервер. Это добавляет ежемесячные расходы, как и у любого традиционного сервера. Однако количество вызовов сервера значительн
```suggestion
- **Стоимость:** Чтобы отображать страницы «налету», должен быть запущен сервер. Это добавляет ежемесячные расходы, как и у любого традиционного сервера. Однако количество вызовов сервера значительно сокращается благодаря универсальному рендерингу, когда браузер берет на себя навигацию на стороне клиента. Снижение затрат возможно за счет использования [пограничного рендеринга](#edge-side-rendering).
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Из коробки, традиционное Vue.js приложение рендерится в браузере (или **на клиенте**). Затем Vue.js генерирует HTML-элементы после того, как браузер загрузит и спарсит весь JavaScript код, содержащий
```suggestion
Из коробки традиционное Vue.js приложение рендерится в браузере (или **на клиенте**). Затем Vue.js генерирует HTML-элементы после того, как браузер загрузит и спарсит весь JavaScript код, содержащий инструкции для создания текущего интерфейса.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Если вы размещаете ваше приложение на [статичном хостинге](/docs/getting-started/deployment#static-hosting) с помощью команд `nuxi generate` или `nuxi build --prerender`, тогда по умолчанию, Nuxt буд
```suggestion
Если вы размещаете ваше приложение на [статичном хостинге](/docs/getting-started/deployment#static-hosting) с помощью команд `nuxi generate` или `nuxi build --prerender`, тогда по умолчанию Nuxt будет рендерить каждую страницу как отдельный статичный HTML-файл.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Чтобы добиться этого, мы можем поменять как пререндерятся маршруты. Просто добавьте это к [вашим hooks](/docs/api/advanced/hooks#nuxt-hooks-build-time) в вашем `nuxt.config.ts`:
```suggestion
Чтобы добиться этого, мы можем поменять способ рендеринга маршрутов. Просто добавьте это к [вашим хукам](/docs/api/advanced/hooks#nuxt-hooks-build-time) в вашем `nuxt.config.ts`:
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Гибридный рендеринг допускает разные правила кэширования для каждого маршрута, используя **Route Rules**, и решает как сервер должен отвечать на новый запрос по заданному URL.
```suggestion
Гибридный рендеринг допускает разные правила кэширования для каждого маршрута, используя **правила маршрутизации**, и решает, как сервер должен отвечать на новый запрос по заданному URL.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Раньше каждый маршрут/страница Nuxt приложения и сервер должны были использовать одинаковый режим рендеринга, универсальный или клиентский. В различных случаях некоторые страницы должны быть созданы
```suggestion
Раньше каждый маршрут/страница Nuxt-приложения и сервер должны были использовать одинаковый режим рендеринга, универсальный или клиентский. В различных случаях некоторые страницы должны быть созданы во время сборки, в то время как другие должны быть отрисованы на клиенте. Например, подумайте о контентных сайтах с админ-частью. Каждая страница с контеном должна быть в первую очередь статической и генерироваться один раз, но админ-часть требует регистрации и ведет себя скорее как динамическое приложение.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Nuxt-сервер будет автоматически регистрировать соответствующие middleware и оборачивать маршруты с обработчиками кэша, используя [Nitro caching layer](https://nitro.unjs.io/guide/cache).
```suggestion
Nuxt-сервер будет автоматически регистрировать соответствующие middleware и оборачивать маршруты с обработчиками кэша, используя [слой кеширования Nitro](https://nitro.unjs.io/guide/cache).
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +    // Перенаправляет legacy URL-адреса
```suggestion
    // Перенаправляет старые URL-адреса
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +- `headers: object`{lang=ts} - Добавьте определенные заголовки в разделы вашего сайта, например, в ваши ресурсы.
```suggestion
- `headers: object`{lang=ts} - Добавляет определенные заголовки в разделы вашего сайта, например, в ваши ассеты.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +- `swr: number | boolean`{lang=ts} - Добавьте заголовки кэша к ответу сервера и кэшируйте его на сервере или обратном прокси-сервере для настраиваемого TTL (time to live - времени жизни). Настройка N
```suggestion
- `swr: number | boolean`{lang=ts} - Добавляет заголовки кэша к ответу сервера и кэширует его на сервере или обратном прокси-сервере для настраиваемого TTL (time to live - времени жизни). Настройка Nitro `node-server` способна кэшировать полный ответ. По истечении срока жизни (TTL) будет отправлен кэшированный ответ, а страница будет перегенерирована в фоновом режиме. Если импользуется `true`, будет добавлен заголовок `stale-while-revalidate` без MaxAge.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Пограничный рендеринг возомжен, благодаря [Nitro](https://nitro.unjs.io), [серверному движку](/docs/guide/concepts/server-engine), который обеспечивает работу Nuxt 3. Он предлагает кроссплатформенную
```suggestion
Пограничный рендеринг возможен, благодаря [Nitro](https://nitro.unjs.io) - [серверному движку](/docs/guide/concepts/server-engine) - который обеспечивает работу Nuxt 3. Он предлагает кроссплатформенную поддержку Node.js, Deno, Cloudflare Workers и других.
```

2024-06-22 18:24 UTC, Hekikai commented on docs/2.guide/1.concepts/3.rendering.md
> +Обратите внимание, что **Гибридный рендеринг** можно использовать при использовании Пограничного рендеринга с правилами маршрутизации.
```suggestion
Обратите внимание, что **гибридный рендеринг** можно использовать при использовании пограничного рендеринга с правилами маршрутизации.
```

2024-06-23 10:41 UTC, Hekikai approved these changes

2024-06-23 11:04 UTC, Ibochkarev approved these changes

2024-06-23 11:05 UTC, merged