Локализация docs/2.guide/2.directory-structure/2.env.md #45
translation-gang/nuxt pull request #206
Opened 2024-06-22 08:25 UTC by jeweler23

### 🔗 Linked issue

resolves [.env](https://github.com/translation-gang/nuxt/issues/45)

### 📚 Description

[docs/2.guide/2.directory-structure/2.env.md](https://nuxt.com/docs/guide/directory-structure/env)

2024-06-22 08:47 UTC, mnenie commented
1. Что то осталось, например: Note that removing a variable from `.env` or removing the `.env` file entirely will not unset values that have already been set.
2. Что то пропущено, например:  :read-more{to="/docs/guide/directory-structure/app-config"}

я бы еще раз все пересмотрел, есть что пропущено и не учтено.

2024-06-22 10:28 UTC, jeweler23 commented
спасибо за замечания, поправил

2024-06-22 18:10 UTC, Hekikai requested changes

2024-06-22 18:10 UTC, Hekikai commented on docs/2.guide/2.directory-structure/2.env.md
> +Добавьте файл .env в [`.gitignore`](/docs/guide/directory-structure/gitignore) для сохранения конфиденциальных данных перед пушем в ваш репозиторий
```suggestion
Добавьте файл .env в [`.gitignore`](/docs/guide/directory-structure/gitignore) для сохранения конфиденциальных данных перед пушем в ваш репозиторий.
```

2024-06-22 18:10 UTC, Hekikai commented on docs/2.guide/2.directory-structure/2.env.md
> +Nuxt CLI имеет втроенную поддержку [dotenv](https://github.com/motdotla/dotenv) в режиме разработки,а также при запуске сборки [`nuxi build`](/docs/api/commands/build) и генерации [`nuxi generate`](/
```suggestion
Nuxt CLI имеет встроенную поддержку [dotenv](https://github.com/motdotla/dotenv) в режиме разработки,а также при запуске сборки [`nuxi build`](/docs/api/commands/build) и генерации [`nuxi generate`](/docs/api/commands/generate).
```

2024-06-22 18:10 UTC, Hekikai commented on docs/2.guide/2.directory-structure/2.env.md
> +На данном этапе ваши `.env` файлы не будут считываться. Это связано с обеспечением совместимости в различных средах развертывания. В некоторых средах традиционная файловая система может быть недоступ
Тут и ниже местами поменялись предложения, исправь это  
Причем довольно много) потом пингани меня еще раз, я проверю

2024-06-22 18:10 UTC, Hekikai commented on docs/2.guide/2.directory-structure/2.env.md
> +: Подробнее {to="/docs/guide/going-further/runtime-config"}
Это переводить не нужно! Это компонент
```suggestion
:read-more{to="/docs/guide/going-further/runtime-config"}
```

2024-06-22 18:10 UTC, Hekikai commented on docs/2.guide/2.directory-structure/2.env.md
> +:: note
```suggestion
::note
```

2024-06-22 18:14 UTC, mnenie commented on docs/2.guide/2.directory-structure/2.env.md
> +: Подробнее {to="/docs/guide/going-further/runtime-config"}
@jeweler23 тут я не это имел ввиду )
ты в последнем предложении видимо по ошибке убрал :read-more{to="/docs/guide/directory-structure/app-config"}

2024-06-22 18:50 UTC, jeweler23 commented
@Hekikai исправил замечания

2024-06-23 10:42 UTC, Hekikai approved these changes

2024-06-23 10:43 UTC, mnenie approved these changes

2024-06-23 11:04 UTC, merged