Локализация файлов из docs/guide/directory
translation-gang/nuxt pull request #207
Opened 2024-06-23 02:22 UTC by JonikUl

### 🔗 Linked issue

resolves #37

### 📚 Description

 docs/guide/directory-structure/nuxt.md
 docs/guide/directory-structure/output.md
 docs/guide/directory-structure/assets.md
 docs/guide/directory-structure/content.md
 docs/guide/directory-structure/modules.md
 docs/guide/directory-structure/node_modules.md
 docs/guide/directory-structure/public.md
 docs/guide/directory-structure/utils.md
 docs/guide/directory-structure/gitignore.md
 docs/guide/directory-structure/nuxtignore.md
 docs/guide/directory-structure/app.md
 docs/guide/directory-structure/error.md
 docs/guide/directory-structure/nuxt-config.md
 docs/guide/directory-structure/package.md
 docs/guide/directory-structure/tsconfig.md

2024-06-23 05:00 UTC, Ibochkarev approved these changes

2024-06-23 08:17 UTC, Hekikai requested changes

2024-06-23 08:17 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.assets.md
> +description: "Директория assets/ используется для добавления всех ресурсов веб-сайта, которые будет обрабатывать инструмент сборки."
Я бы оставил "ассетов"

2024-06-23 08:17 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.modules.md
> +    name: 'привет'
Давай не будем переводить, это же просто название модуля

2024-06-23 08:17 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.modules.md
> +```bash [Стректура директории]
```suggestion
```bash [Структура директории]
```

2024-06-23 08:17 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.public.md
> +description: "Директория public/ используется для обслуживания статических ресурсов веб-сайта."
Я бы тут оставил ресурсов, чтобы было разделение на ассеты (/assets) и ресурсы из паблик директории (/public)

2024-06-23 08:17 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.utils.md
> +description: Используйте директорию utils/ для автоматического импорта ваших служебных функций во все приложение.
```suggestion
description: Используйте директорию utils/ для автоматического импорта ваших служебных функций во всё приложение.
```

2024-06-23 08:17 UTC, Hekikai commented on docs/2.guide/2.directory-structure/3.error.md
> +Страница ошибок имеет единственно свойство - `error`, которое содержит ошибку, которую нужно обработать.
```suggestion
Страница ошибок имеет единственный входной параметр - `error`, содержащий ошибку, которую нужно обработать.
```

2024-06-24 06:59 UTC, Hekikai approved these changes

2024-06-24 07:28 UTC, merged