feat(docs): Локализация раздела pages
translation-gang/nuxt pull request #212
Opened 2024-06-23 10:45 UTC by jeweler23

### 🔗 Linked issue

[resolves #42](https://nuxt-ru.vercel.app/docs/guide/directory-structure/pages)

### 📚 Description

перевод раздела docs/directory-structure/1.pages.md

2024-06-23 11:05 UTC, Hekikai requested changes

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Полный список устанавливаемых параметров можно посмотреть [здесь](https://ru.vuejs.org/api/built-in-components.html#transition) или прочитайте [подробнее о работе переходов](https://ru.vuejs.org/guid
```suggestion
Полный список устанавливаемых параметров можно посмотреть [здесь](https://ru.vuejs.org/api/built-in-components.html#transition) или прочитайте [подробнее о работе transition](https://ru.vuejs.org/guide/built-ins/transition.html#transition).
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Вы можете определить middleware для применения перед загрузкой страницы. Оно будет объединено со всеми другими middleware, используемыми в любых соответствующих родительских/дочерних маршрутах. Это м
```suggestion
Вы можете определить middleware для применения перед загрузкой страницы. Оно будет объединено со всеми другими middleware, используемыми в любых соответствующих родительских/дочерних маршрутах. Это может быть строка, функция (анонимная/встроенная middleware функция, использующая [паттерн глобальных хуков перед переходом](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards)), или массив строк/функций. [Подробнее об именованных middleware](/docs/guide/directory-structure/middleware).
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Вы можете задать имя ждя маршрута страницы.
```suggestion
Вы можете задать имя для маршрута страницы.
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +### Типизация Пользовательских Метаданных
```suggestion
### Типизация Пользовательских Мета-данных
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Если вы хотите добавить типизацию метаданным на ваши страницы, вы можете сделать безопасным способом. Можно дополнить тип объекта, принимаемого `definePageMeta`:
```suggestion
Если вы хотите добавить типизацию мета-данных на ваши страницы, вы можете сделать это безопасным способом. Можно дополнить тип объекта, принимаемого `definePageMeta`:
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> -To navigate between pages of your app, you should use the [`<NuxtLink>`](/docs/api/components/nuxt-link) component.
Удален перевод, верни обратно))

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> -This component is included with Nuxt and therefore you don't have to import it as you do with other components.
А вот, вот это пропущено

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Для навигации между страницами в вашем приложении, вы можете использовать компонент [`<NuxtLink>`](/docs/api/components/nuxt-link).
```suggestion
Для навигации между страницами в вашем приложении вы можете использовать компонент [`<NuxtLink>`](/docs/api/components/nuxt-link).
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Например, ссылна на страницу `index.vue` в папке `pages`:
```suggestion
Например, ссылка на страницу `index.vue` в папке `pages`:
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Вы можете определить страницу как [только на стороне клиента](/docs/guide/directory-structure/components#client-components), для этого добавиьте суффикс `.client.vue`.Ни одно из содержимых этой стран
```suggestion
Вы можете определить страницу как [только на стороне клиента](/docs/guide/directory-structure/components#client-components), для этого добавьте суффикс `.client.vue`. Ни одно из содержимых этой страницы не будет отображаться на сервере.
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Страницы, предназначенные только для сервера, должны иметь один корневой элемент. (Комментарии HTML также считаются элементами).
```suggestion
Страницы, предназначенные только для сервера, должны иметь один корневой элемент. (HTML-комментарии также считаются элементами).
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Мультистраничная Диреткория
```suggestion
## Мультистраничная Директория
```

2024-06-23 11:05 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Однако вы можете использовать [Nuxt Layers](/docs/getting-started/layers) для создания группирования страниц вашего приложения:
```suggestion
Однако, вы можете использовать [слои Nuxt](/docs/getting-started/layers) для создания групп страниц вашего приложения:
```

2024-06-23 11:07 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Мультистраничная Диреткория
Давай директория с маленькой буквы начинать

2024-06-23 11:12 UTC, mnenie commented
@jeweler23 у тебя возможно стоит в vs code авто форматирование на ctrl/cmd + s
будь повнимательнее, отключи лучше это здесь
иначе код в файлах тоже портится, и получается -> где-то кавычки лишние, где-то что-то убрано ...

2024-06-23 11:13 UTC, mnenie commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Мультистраничная Диреткория
я бы еще многостраничная оставил )

2024-06-24 18:57 UTC, jeweler23 commented on docs/2.guide/2.directory-structure/1.pages.md
> +head.title: "Страницы/"
@Hekikai title не переводим, а head.title переводим?

2024-06-24 19:04 UTC, jeweler23 commented on docs/2.guide/2.directory-structure/1.pages.md
> +Файл `pages/index.vue` будет иметь маршрут `/` в вашем приложении.
да... удалил, извиняюсь за самодеятельность

2024-06-24 19:25 UTC, jeweler23 commented on docs/2.guide/2.directory-structure/1.pages.md
> +const props = defineProps(["foobar"]);
звучит как план :D

2024-06-24 19:59 UTC, jeweler23 commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Мультистраничная Диреткория
как в итоге лучше?)

2024-06-24 20:06 UTC, jeweler23 commented
@Hekikai @Ibochkarev @mnenie исправил замечания, перепроверьте, пожалуйста

2024-06-25 02:53 UTC, Ibochkarev requested changes

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +head.title: "Страницы/"
```suggestion
head.title: "pages/"
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +Это означает, что когда маршрут рендерится на сервере или генерируется статически, вы сможете увидеть его содержимое правильно, но когда вы перейдете к этому маршруту во время навигации на стороне кл
```suggestion
Это означает, что когда маршрут рендерится на сервере или генерируется статически, вы сможете увидеть его содержимое правильно, но когда вы перейдете к этому маршруту во время навигации на клиенте, переход между маршрутами будет неудачным, и вы увидите, что маршрут не рендерится.
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +  <!-- Эта страница не будет отображаться при изменении маршрута во время навигации на стороне клиента из-за этого комментария -->
```suggestion
  <!-- Эта страница не будет отображаться при изменении маршрута во время навигации на клиенте из-за этого комментария -->
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +  <div>И не будет рендериться при изменении маршрута во время навигации на стороне клиента</div>
```suggestion
  <div>И не будет рендериться при изменении маршрута во время навигации на клиенте</div>
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Динамические Маршруты
```suggestion
## Динамические маршруты
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Универсальный Маршрут
```suggestion
## Универсальный маршрут
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Вложенные Маршруты
```suggestion
## Вложенные маршруты
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +### Ключи Дочерних Маршрутов
```suggestion
### Ключи дочерних маршрутов
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +### Специальные Мета-данные
```suggestion
### Специальные мета-данные
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +Когда вы хотите сохранить состояние родительских маршрутов, тогда используйте следующий синтаксис: `<NuxtPage keepalive />`. Вы также можете передать входные параметры в `<KeepAlive>` (см. полный спи
```suggestion
Если вы хотите сохранить состояние родительских маршрутов, тогда используйте следующий синтаксис: `<NuxtPage keepalive />`. Вы также можете передать входные параметры в `<KeepAlive>` (см. полный список [здесь](https://ru.vuejs.org/api/built-in-components.html#keepalive)).
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Программная Навигация
```suggestion
## Программная навигация
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Страницы на стороне клиента
```suggestion
## Клиентские страницы
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +Вы можете определить страницу как [только на стороне клиента](/docs/guide/directory-structure/components#client-components), для этого добавьте суффикс `.client.vue`. Ни одно из содержимых этой стран
```suggestion
Вы можете определить страницу как [только на клиенте](/docs/guide/directory-structure/components#client-components), для этого добавьте суффикс `.client.vue`. Ни одно из содержимых этой страницы не будет отображаться на сервере.
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Страницы на стороне сервера
```suggestion
## Серверные страницы
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +Вы можете определить страницу как [только на стороне сервера](/docs/guide/directory-structure/components#server-components), добавив суффикс `.server.vue`. Хотя вы сможете перейти на эту страницу с п
```suggestion
Вы можете определить страницу как [только на сервере](/docs/guide/directory-structure/components#server-components), добавив суффикс `.server.vue`. Хотя вы сможете перейти на эту страницу с помощью навигации на стороне клиента, управляемой `vue-router`, она будет автоматически рендериться серверным компонентом, что означает, что код, необходимый для рендеринга страницы, не будет включен в ваш клиентский бандл.
```

2024-06-25 02:53 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Пользовательский Роутинг
```suggestion
## Пользовательский роутинг
```

2024-06-25 06:04 UTC, jeweler23 commented on docs/2.guide/2.directory-structure/1.pages.md
> +### Типизация Пользовательских Мета-данных
@Ibochkarev тогда тут сделать 310 Типизация пользовательских мета-данных?

2024-06-25 07:34 UTC, Hekikai requested changes

2024-06-25 07:34 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Для уменьшения размера вашего бандла, эта директория является **опциональной**, то есть [`vue-router`](https://router.vuejs.org) не будет включен в проект, если вы используете только [`app.vue`](/doc
```suggestion
Для уменьшения размера вашего бандла эта директория является **опциональной**, то есть [`vue-router`](https://router.vuejs.org) не будет включен в проект, если вы используете только [`app.vue`](/docs/guide/directory-structure/app). Чтобы использовать многостраничный режим, установите `pages: true` в `nuxt.config` или создайте файл [`app/router.options.ts`](/docs/guide/going-further/custom-routing#using-approuteroptions).
```

2024-06-25 07:34 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Если вы используете Composition API, доступ к маршрутизатору можно получить, вызвав глобальную функцию [`useRoute`](/docs/api/composables/use-route), которая позволит вам получить доступ к маршруту т
```suggestion
Если вы используете Composition API, то доступ к объекту маршрута можно получить, вызвав глобальную функцию [`useRoute`](/docs/api/composables/use-route), которая позволит вам получить доступ к маршруту так же, как `this.$route` в Options API.
```

2024-06-25 07:34 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Если вы хотите больше контролировать повторный рендер `<NuxtPage>` компонента (например, для переходов), то вы можете передавать строку или функцию во входной параметр`pageKey`, или определить значен
```suggestion
Если вы хотите больше контролировать повторный рендер `<NuxtPage>` компонента (например, для переходов), то вы можете передавать строку или функцию во входной параметр`pageKey` или определить значение `key` через `definePageMeta`:
```

2024-06-25 07:34 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +Вы можете определить middleware для применения перед загрузкой страницы. Оно будет объединено со всеми другими middleware, используемыми в любых соответствующих родительских/дочерних маршрутах. Это м
```suggestion
Вы можете определить middleware для применения перед загрузкой страницы. Оно будет объединено со всеми другими middleware, используемыми в любых соответствующих родительских/дочерних маршрутах. Это может быть строка, функция (анонимная/встроенная middleware функция, использующая [паттерн глобальных хуков перед переходом](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards)), или массив строк/функций. [Подробнее об именованных middleware](/docs/guide/directory-structure/middleware).
```

2024-06-25 07:35 UTC, Hekikai commented
@jeweler23 привет! Сейчас намного лучше, спасибо! Ты можешь добавить мои исправления прям из интерфейса гитхаба, чтобы не делать доп. работу)

2024-06-25 07:40 UTC, Hekikai commented on docs/2.guide/2.directory-structure/1.pages.md
> +head.title: "Страницы/"
@jeweler23 ну мы же хотим такого?) тогда не переводим
![image](https://github.com/translation-gang/nuxt/assets/90565172/2de1495c-573b-465c-9d4c-ebbb4304315e)

2024-06-25 08:37 UTC, jeweler23 commented
@Hekikai привет! спасибо за проверку и замечания, внес твои коррективы. Увы, я пока пользователь гита на уровне pull/push :D Поэтому еще не знаю как сразу в интерфейсе скорректировать можно

2024-06-25 18:00 UTC, Hekikai approved these changes

2024-06-26 03:08 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +Если вы хотите больше контролировать повторный рендер `<NuxtPage>` компонента (например, для переходов), то вы можете передавать строку или функцию во входной параметр`pageKey` или определить значени
```suggestion
Если вы хотите больше контролировать повторный рендер `<NuxtPage>` компонента (например, для переходов), то вы можете передавать строку или функцию во входной параметр `pageKey` или определить значение `key` через `definePageMeta`:
```

2024-06-26 03:11 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +### Типизация пользовательских мета-данных
```suggestion
### Типизация Пользовательских Мета-данных
```

2024-06-26 03:12 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +## Мультистраничная директория
```suggestion
## Многостраничная директория
```

2024-06-26 03:14 UTC, Ibochkarev commented on docs/2.guide/2.directory-structure/1.pages.md
> +### Специальные мета-данные
```suggestion
### Специальные Мета-данные
```

2024-06-26 03:17 UTC, Ibochkarev approved these changes

2024-06-26 03:17 UTC, merged