feat(docs): Добавлен перевод для useNuxtApp (#88)
translation-gang/nuxt pull request #235
Opened 2024-06-30 19:21 UTC by Hekikai

### 🔗 Linked issue

resolves #88 

### 📚 Description

Добавлен перевод для `useNuxtApp`

2024-06-30 19:21 UTC, Hekikai commented on docs/3.api/2.composables/use-nuxt-app.md
> +
```suggestion
```

2024-06-30 19:48 UTC, mnenie commented on docs/3.api/2.composables/use-nuxt-app.md
> +Нативная поддержка async- контекста в настоящее время работает в Bun и Node.
```suggestion
Нативная поддержка async-контекста в настоящее время работает в Bun и Node.
```

2024-06-30 19:50 UTC, mnenie commented
тут тоже надо решить, что лучше оставить, потому что где-то "хукам времени выполнения", а где-то "runtime-хуки"

2024-07-01 01:21 UTC, Ibochkarev requested changes

2024-07-01 01:21 UTC, Ibochkarev commented on docs/3.api/2.composables/use-nuxt-app.md
> +`ssrContext` генерируется во время рендеринга на стороне сервера и доступен только на стороне сервера.
```suggestion
`ssrContext` генерируется во время рендеринга на сервере и доступен только на сервере.
```

2024-07-01 01:21 UTC, Ibochkarev commented on docs/3.api/2.composables/use-nuxt-app.md
> +`payload` передает данные и переменные состояния со стороны сервера на сторону клиента. Следующие ключи будут доступны клиенту после того, как они будут переданы со стороны сервера:
```suggestion
`payload` передает данные и переменные состояния с сервера на клиента. Следующие ключи будут доступны клиенту после того, как они будут переданы с сервера:
```

2024-07-01 01:21 UTC, Ibochkarev commented on docs/3.api/2.composables/use-nuxt-app.md
> +Используйте `nuxtApp.isHydrating` (boolean), чтобы проверить, гидрируется ли приложение Nuxt на стороне клиента.
```suggestion
Используйте `nuxtApp.isHydrating` (boolean), чтобы проверить, гидрируется ли приложение Nuxt на клиенте.
```

2024-07-01 01:21 UTC, Ibochkarev commented on docs/3.api/2.composables/use-nuxt-app.md
> +Vue.js Composition API (и композаблы Nuxt аналогично) работают в зависимости от неявного контекста. Во время жизненного цикла Vue устанавливает временный экземпляр текущего компонента (а Nuxt - време
```suggestion
Vue.js Composition API (и композаблы Nuxt аналогично) работают в зависимости от неявного контекста. Во время жизненного цикла Vue устанавливает временный экземпляр текущего компонента (а Nuxt - временный экземпляр nuxtApp) в глобальную переменную и отменяет его в том же тике. При рендеринге на сервере происходит множество запросов от разных пользователей, а nuxtApp работает в одном глобальном контексте. Поэтому Nuxt и Vue немедленно отменяют установку этого глобального инстанса, чтобы избежать утечки общей ссылки между двумя пользователями или компонентами.
```

2024-07-01 04:52 UTC, Ibochkarev commented on docs/3.api/2.composables/use-nuxt-app.md
> +- `data` (object) - Когда вы получаете данные из конечной точки API, используя либо [`useFetch`](/docs/api/composables/use-fetch), либо [`useAsyncData`](/docs/api/composables/use-async-data), результ
Нет, это же тип

2024-07-01 07:08 UTC, Ibochkarev approved these changes

2024-07-01 07:28 UTC, merged