feat(docs): Локализация docs/guide/recipes/custom-routing.md
translation-gang/nuxt pull request #238
Opened 2024-07-01 10:13 UTC by mnenie

### 🔗 Linked issue

resolves #69

### 📚 Description

Переведена страница docs/guide/recipes/custom-routing.md

2024-07-01 10:16 UTC, Hekikai requested changes

2024-07-01 10:16 UTC, Hekikai commented on docs/2.guide/4.recipes/1.custom-routing.md
> +Можно добавить больше файлов опций маршрутизатора, добавив файлы в хук `pages:routerOptions` hook. Более поздние элементы массива переопределяют более ранние.
```suggestion
Можно добавить больше файлов опций маршрутизатора, добавив файлы в хук `pages:routerOptions`. Более поздние элементы массива переопределяют более ранние.
```

2024-07-01 10:16 UTC, Hekikai commented on docs/2.guide/4.recipes/1.custom-routing.md
> +Вы можете включить хэш-историю в SPA режиме с помощью `hashMode` [конфига](/docs/api/nuxt-config#router). В этом режиме маршрутизатор использует символ хэша (#) перед фактическим URL-адресом, который
```suggestion
Вы можете включить хэш-историю в SPA-режиме с помощью `hashMode` [конфига](/docs/api/nuxt-config#router). В этом режиме маршрутизатор использует символ хэша (#) перед фактическим URL-адресом, который передается внутрь. Если этот режим включен, **URL никогда не отправляется на сервер** и **SSR не поддерживается**.
```

2024-07-01 10:24 UTC, Ibochkarev approved these changes

2024-07-02 02:23 UTC, alexeyvokin commented on docs/2.guide/4.recipes/1.custom-routing.md
> +Можно добавить больше файлов опций маршрутизатора, добавив файлы в хук `pages:routerOptions`. Более поздние элементы массива переопределяют более ранние.
```suggestion
Можно добавить больше файлов опций маршрутизатора, добавив файлы в хуке `pages:routerOptions`. Более поздние элементы массива переопределяют более ранние.
```

2024-07-02 02:23 UTC, alexeyvokin commented on docs/2.guide/4.recipes/1.custom-routing.md
> +Добавление файла опций маршрутизатора в этот хук включит постраничную навигацию, если только не задано значение `optional`, в этом случае она будет применяться только тогда, когда постраничная навига
```suggestion
Добавление файла опций маршрутизатора в этом хуке включит постраничную навигацию, если только не задано значение `optional`, в этом случае она будет применяться только тогда, когда постраничная навигация уже включена.
```

2024-07-02 02:24 UTC, alexeyvokin commented on docs/2.guide/4.recipes/1.custom-routing.md
> +Добавление файла опций маршрутизатора в этот хук включит постраничную навигацию, если только не задано значение `optional`, в этом случае она будет применяться только тогда, когда постраничная навига
хотя, конечно, можно так и так)

2024-07-02 05:10 UTC, Hekikai approved these changes

2024-07-02 05:15 UTC, merged