Update 2.vuejs-development.md
translation-gang/nuxt pull request #7
Opened 2024-05-31 14:21 UTC by AndrewGanzha

### 🔗 Linked issue

### 📚 Description

2024-05-31 14:58 UTC, Hekikai requested changes

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +title: "Vue.js разработка"
Vue.js Development - Разработка при помощи Vue.js

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +description: "Nuxt использует Vue.js и добавляет такие функции, как автоматический импорт компонентов, файловую маршрутизацию и компоновку для более удобного использования SSR."
Nuxt использует Vue.js и добавляет такие функции как: автоматический импорт компонентов, файловую маршрутизацию и composables для более удобного использования SSR.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Nuxt интегрирует Vue 3, новую основную версию Vue, которая предоставляет пользователям Nuxt новые шаблоны.
...пользователям Nuxt новые паттерны для разработки.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Хотя для использования Nuxt не требуется глубоких знаний Vue, мы рекомендуем вам прочитать документацию и просмотреть некоторые примеры на [vuejs.org](https://vuejs.org).
примеры на [ru.vuejs.org](https://ru.vuejs.org)

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +- Шаблоны на основе компонентов, сохраняя HTML в качестве стандартного языка разметки в сети Интернет, позволяют использовать интуитивно понятные шаблоны, чтобы ваш интерфейс оставался последовательн
Шаблоны на основе компонентов, сохраняя HTML в качестве стандартного языка разметки, позволяют использовать интуитивно понятные паттерны, чтобы ваш интерфейс оставался консистентным и при этом мощным.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +- От небольших проектов до крупных веб-приложений, Vue продолжает хорошо работать в любом масштабе, чтобы ваше приложение продолжало приносить пользу вашим пользователям.
...Vue демонстрирует хорошие результаты при скалировании, что позволяет вашему приложению приносить пользу вашим пользователям.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +## Vue с Nuxt
Vue вместе Nuxt

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +[Vue’s однофайловые компоненты](https://v3.vuejs.org/guide/single-file-component.html) (SFC или `*.vue` файлы) инкапсулируют разметку (`<template>`), логику (`<script>`) и стили (`<style>`) Vue компо
[Однофайловые компоненты Vue](ПРИЛОЖИ СЮДА АКТУАЛЬНУЮ ССЫЛКУ ИЗ НАШЕЙ ДОКИ!)  
с помощью [HMR], который предлагает плавный DX.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Каждый компонент Vue, созданный в директории [`components/`](/docs/guide/directory-structure/components) проекта Nuxt будет доступен в вашем проекте без необходимости его импорта. Если компонент нигд
проекта Nuxt, будет доступен   
Если компонент нигде не используется, он не будет включен в ваш production-код.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +:Прочитайте больше{to="/docs/guide/concepts/auto-imports"}
Узнать больше

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +MБольшинству приложений требуется несколько страниц и способ навигации между ними. Это называется **маршрутизацией**. Nuxt использует директорию [`pages/`](/docs/guide/directory-structure/pages) и со
Убрать в начале M  
 с использованием официальной [библиотеки Vue Router]

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +:Прочитайте больше{to="/docs/getting-started/routing"}
Узнать больше

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
>  :link-example{to="/docs/examples/features/auto-imports"}
Пример

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Vue Virtual DOM (VDOM) был переписан с нуля и обеспечивает лучшую производительность рендеринга. Кроме того, при работе с скомпилированными однофайловыми компонентами компилятор Vue может дополнитель
Виртуальное DOM-дерево (VDOM) Vue было переписано с нуля, и теперь обеспечивает лучшую производительность рендеринга. Кроме того - при работе с скомпилированными SFC - компилятор Vue может дополнительно оптимизировать их во время сборки, разделяя статическую и динамическую разметки.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Это приводит к более быстрому первому рендерингу (созданию компонента) и обновлениям, а также к меньшему использованию памяти. В Nuxt 3 это также обеспечивает более быстрый рендеринг на стороне серве
...к более быстрым...

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +### Меньший размер проекта
Меньше размер бандла

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +В Vue 3 и Nuxt 3 основное внимание было уделено уменьшению размера пакета. В версии 3 большая часть функциональности Vue, включая директивы шаблонов и встроенные компоненты, поддерживает древовидную
Во Vue 3 и Nuxt 3 основное внимание было уделено уменьшению размера итогового бандла. Начиная с 3 версии, большая часть функциональности Vue, включая директивы шаблонов и встроенные компоненты, теперь tree-shakable. Ваш итоговый бандл не будет включать их, если вы их не используете.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Единственный способ предоставить данные и логику компонентам в Vue 2 — через Options API, который позволяет возвращать данные и методы в шаблон с предопределенными свойствами, такими как `data` and `
такими как `data` and `methods` - переведи and)))

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +[Composition API](https://vuejs.org/guide/extras/composition-api-faq.html) представленный в Vue 3, не является заменой Options API, но обеспечивает лучшее повторное использование логики во всем прило
[Composition API](https://vuejs.org/guide/extras/composition-api-faq.html), представленный во Vue 3, не является заменой Options API, а обеспечивает удобное использование повторяемой логики во всем приложении и является более естественным способом группировки кода по общему признаку в сложных компонентах.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Используется с `setup` написанном как атрибут в `<script>` вот приведенный выше компонент, переписанный с использованием Composition API и автоматически импортированных API-интерфейсов реактивности и
Composition API используется с атрибутом `setup` в теге `<script>`. Компонент ниже переписан с использованием Composition API и автоматически импортированного API реактивности из Nuxt 3:

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +- Используйте автоматически импортированные [реактивные функции](https://vuejs.org/api/reactivity-core.html) из Vue и Nuxt 3 [встроенные компонуемые элемменты](/docs/api/composables/use-async-data).
импортированные [функции реактивности](ДОБАВИТЬ ССЫЛКУ) из Vue и [встроенные композаблы](/docs/api/composables/use-async-data)Nuxt 3.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +- Напишите свои собственные автоматически импортируемые повторно используемые функции в файле [`composables/` директории](/docs/guide/directory-structure/composables).
- Напишите свои собственные автоматические импортируемые композаблы в [`composables/` директории](/docs/guide/directory-structure/composables).

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +И Vue 3, и Nuxt 3 написаны на TypeScript. Полностью типизированная кодовая база предотвращает ошибки и документирует использование API. Это не означает, что вам нужно писать приложение на TypeScript,
В Nuxt 3 вы можете включить TS, переименовав файл с `.js` на `.ts` , или добавить `<script setup lang="ts">` в компонент.

2024-05-31 14:58 UTC, Hekikai commented on docs/2.guide/1.concepts/2.vuejs-development.md
> +Прочтите подробности о TypeScript в Nuxt 3.
Узнать больше о TypeScript в Nuxt 3.

2024-06-01 07:00 UTC, Ibochkarev commented
@Hekikai @AndrewGanzha спасибо!

2024-06-01 07:00 UTC, Ibochkarev approved these changes

2024-06-01 07:00 UTC, merged